apiVersion: securitygroup/v1
kind: SecurityGroup
metadata:
  name: vpc-security-group
spec:
  description: "Allow only specific IP ranges"
  ingress:
    - cidr: "192.168.0.0/16"
      protocol: "tcp"
      portRange: "80,443"
  egress:
    - cidr: "0.0.0.0/0"
      protocol: "tcp"
      portRange: "80,443"
