"""Utility for generating SaaS specification dictionaries."""

from typing import Dict, Any


def generate_saas_spec(solution: str, biz_model: str) -> Dict[str, Any]:
    """Create a basic spec dictionary for the SaaS project."""
    spec = {
        "project": "AutoGenerated SaaS",
        "description": solution,
        "billing": biz_model,
        "modules": [
            # 자동 추출된 기능 모듈들...
        ],
    }
    return spec
