apiVersion: v1
kind: Namespace
metadata: { name: logging }
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata: { name: vin-es, namespace: logging }
spec:
  version: 8.13.2
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata: { name: vin-kb, namespace: logging }
spec:
  version: 8.13.2
  count: 1
  elasticsearchRef: { name: vin-es }
