apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: { name: vinfinity-api }
spec:
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 1
      - pause: { duration: 5m }
      - setWeight: 25
      - pause: { duration: 15m }
      - setWeight: 100
  selector:
    matchLabels: { app: vinfinity-api }
  template:
    metadata: { labels: { app: vinfinity-api } }
    spec:
      containers:
      - name: api
        image: ghcr.io/...:{{ .SHA }}
        ports: [{ containerPort: 8000 }]
