version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  kafka:
    image: bitnami/kafka:3
    environment:
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ["29092:29092"]

  feast-ingest:
    build: .
    command: python feast_stream_ingest.py
    depends_on: [kafka, redis]
    environment:
      - KAFKA_BROKERS=kafka:9092
