name: Codex Cleanup

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({ owner: 'sunwoopark0512', repo: 'Auto_Pipeline' });
            for (const pr of prs.data) {
              if (pr.draft && pr.updated_at < new Date(Date.now() - 7*24*60*60*1000).toISOString()) {
                await github.rest.pulls.update({ ...pr, state: 'closed' });
              }
            }
