name: Sync Secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Put OpenAI key
        run: |
          aws secretsmanager put-secret-value --secret-id /vinfinity/OPENAI_API_KEY --secret-string "$OPENAI_API_KEY"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
