name: CI

on:
  push:
    branches: ["main", "master"]
  schedule:
    - cron: '0 5 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_HOOK_DB_ID: ${{ secrets.NOTION_HOOK_DB_ID }}
      NOTION_KPI_DB_ID: ${{ secrets.NOTION_KPI_DB_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: python run_pipeline.py

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "CI pipeline completed on `${{ github.ref }}` with result `${{ job.status }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
