name: Codex Branch Cleanup

on:
  schedule:
    - cron: "30 0 * * *"  # daily at 00:30 UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete stale codex branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        shell: bash
        run: |
          set -euo pipefail
          DAYS=7
          api() { curl -s -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "$@"; }

          mapfile -t branches < <(
            api "https://api.github.com/repos/$OWNER/$REPO/branches?per_page=100" \
            | jq -r '.[].name' | grep '-codex/'
          )
          for br in "${branches[@]}"; do
            pr_state=$(api "https://api.github.com/repos/$OWNER/$REPO/pulls?state=all&head=$OWNER:$br" \
                       | jq -r '.[0].state // empty')
            last_date=$(api "https://api.github.com/repos/$OWNER/$REPO/commits/$br" \
                       | jq -r '.commit.author.date')
            last_ts=$(date -d "$last_date" +%s)
            if [[ "$pr_state" == "closed" || "$last_ts" -lt $(date -d "$DAYS days ago" +%s) ]]; then
              echo "Deleting $br"
              api -X DELETE "https://api.github.com/repos/$OWNER/$REPO/git/refs/heads/$br"
            fi
          done

