name: Daily Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"   # UTC 매일 02:00 (KST 11:00)

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run daily pipeline
        run: python run_pipeline.py --topic "daily-keyword" --token $WORDPRESS_API_TOKEN
