name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker tag your-image-name your-repo/your-image-name:latest
          docker push your-repo/your-image-name:latest
      - name: Deploy to server
        run: |
          ssh user@server "docker pull your-repo/your-image-name:latest && docker run -d -p 5000:5000 your-repo/your-image-name"
