name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Smoke test freshly built image
        run: |
          docker run --rm -e DRY_RUN=1 ghcr.io/${{ github.repository }}:${{ github.sha }} run_pipeline --dry-run
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure K8s OIDC
        uses: azure/k8s-set-context@v1
        with:
          method: oidc
          cluster-type: k8s
          resource-group: ${{ secrets.K8S_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.K8S_CLUSTER_NAME }}
      - name: Rollout
        run: |
          kubectl rollout restart deploy/auto-pipeline
          kubectl rollout status deploy/auto-pipeline --timeout=120s --watch
