name: Graphics CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/graphic_generator/**'
      - 'tests/test_graphic_generator.py'
      - '.github/workflows/graphics-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/graphic_generator/**'
      - 'tests/test_graphic_generator.py'
      - '.github/workflows/graphics-ci.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov black isort pylint
        pip install -r requirements.txt

    - name: Code formatting check
      run: |
        black --check src/graphic_generator tests/test_graphic_generator.py
        isort --check-only --diff src/graphic_generator tests/test_graphic_generator.py

    - name: Lint check
      run: |
        pylint src/graphic_generator tests/test_graphic_generator.py

    - name: Run tests
      run: |
        PYTHONPATH=src pytest tests/test_graphic_generator.py -v --cov=src/graphic_generator --cov-report=xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ github.sha }}
        path: |
          ./coverage.xml
          .pytest_cache
          ./output
        retention-days: 14
