name: Main CI

permissions:
  id-token: write

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        run: pytest --cov=./ --cov-report=xml --cov-fail-under=80 -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          slug: openai/Auto_Pipeline
          fail_ci_if_error: true
