name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint opentelemetry-sdk opentelemetry-exporter-otlp-proto-http
      - name: Lint
        run: pylint run_pipeline.py || true
      - name: Test
        run: pytest -q
      - name: Run pipeline
        run: python scripts/run_pipeline.py
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --report-format sarif --report-path gitleaks.sarif"
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks
