name: Publishers Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  publishers-test:
    needs: lint-test
    runs-on: ubuntu-latest
    env:
      DRYRUN: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements-dev.txt
      - run: pytest tests/test_publishers.py -q
