name: Python Tests

on:
  push:
    paths: ["**.py", "tests/**", ".github/workflows/python-tests.yml"]
  pull_request:
    paths: ["**.py", "tests/**", ".github/workflows/python-tests.yml"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pytest
      - name: Run tests
        run: pytest
