name: Release Docker
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Smoke test image (DRY_RUN)
        run: |
          docker run --rm -e DRY_RUN=1 ghcr.io/${{ github.repository }}:${{ github.ref_name }} run_pipeline --dry-run
