name: Build & Publish API
on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "Dockerfile"
      - ".github/workflows/release-docker.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dev deps & run pre-commit
        run: |
          pip install -r requirements-dev.txt
          pre-commit run --all-files --show-diff-on-failure
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
      - name: Smoke test
        run: docker run --rm -e DRY_RUN=1 ghcr.io/${{ github.repository }}:latest uvicorn api.main:app --host 0.0.0.0 --port 8000 &
