name: Release Docker

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

  api-test:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
      - name: Run & probe
        run: |
          docker run -d -p 8000:8000 --name api -e "API_KEYS=test" ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          sleep 5
          curl -H "X-API-KEY:test" localhost:8000/v1/keywords?limit=1
