name: Rotate Secrets
on:
  workflow_dispatch:
jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Rotate secrets
        id: rotate
        run: python scripts/rotate_secrets.py
  notify:
    needs: rotate
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": ":white_check_mark: Secrets rotation *succeeded* :tada:"
            }
        if: ${{ success() }}
      - uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": ":warning: Secrets rotation *failed!* Check logs <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>."
            }
        if: ${{ failure() }}
