name: Rotate Secrets

on:
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rotate secrets
        run: ./scripts/rotate_secrets.sh
      - if: success()
        uses: slackapi/slack-github-action@v1
        with:
          payload: '{"text":"✅ Secrets rotation succeeded"}'
      - if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          payload: '{"text":":warning: Secrets rotation FAILED – check logs <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"}'
