name: Rotate Secrets
on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  rotate:
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: rotate-secrets
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123:role/gh-rotation
          aws-region: ap-northeast-2
        # Role should allow only secretsmanager:GetSecretValue and ListSecrets

      - id: fetch
        run: |
          echo "OPENAI=$(aws secretsmanager get-secret-value --secret-id openai/prod --query SecretString --output text)" >> $GITHUB_OUTPUT

      - name: Update GH secret
        run: |
          echo "${{ steps.fetch.outputs.OPENAI }}" | gh secret set OPENAI_API_KEY --app actions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
